development:
  cloud_name: 'voting-machine'
  api_key: <%= ENV["cloud_api_key"] %>
  api_secret: <%= ENV["cloud_api_secret"] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: 'voting-machine'
  api_key: <%= ENV["cloud_api_key"] %>
  api_secret: <%= ENV["cloud_api_secret"] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: voting-machine
  api_key: ENV.fetch("cloud_api_key")
  api_secret: ENV.fetch("cloud_api_secret")
  enhance_image_tag: true
  static_file_support: false
